version: "3.9"
services:
  web:
    build:
      context: ./build
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "4000:80"
    volumes:
      - apache_root:/var/www/html
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}      
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  db:
    image: mysql:8.0.31
    restart: unless-stopped
    container_name: mysql 
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}      

volumes:
  apache_root:
  mysql_data:
